[FIX] Minor changes.
aitorbouzas/OCA-helpdesk pull request #6
Opened 2019-06-14 10:54 UTC by alvaroDomatix

1. Updated "Cancel" stage to "Canceled" in helpdesk_data.xml and helpdesk_demo.xml.

2. Added a restriction that does not allow to select any "Assigned user" who is not in the "Team" selected. This restriction forces to select Team before an Assigned user.

3. Added groups to "company_id" in Ticket form to show that field only to multi company users.

2019-06-17 07:29 UTC, aitorbouzas requested changes
Thanks @alvaroDomatix !
As I say in my comments: making a domain for user_id based in the ticket's team is nice but we should not force to pick a team because teams may not be used in most of the cases.

2019-06-17 07:29 UTC, aitorbouzas commented on helpdesk/views/helpdesk_ticket_view.xml
> +                            <field name="user_id" domain="[('id', 'in', user_ids)]" options='{"always_reload": True}'/>
Teams may not always be used, it is ok to only allow user_id to be one of the team but it must not force you to pick a team.

2019-06-17 07:29 UTC, aitorbouzas commented on helpdesk/models/helpdesk_ticket.py
> +        if not self.team_id:
This `if` will not be necessary because we must allow to pick an user without a team.

2019-06-17 07:29 UTC, aitorbouzas commented on helpdesk/demo/helpdesk_demo.xml
> +        <field name="stage_id" ref="helpdesk_ticket_stage_canceled"/>
I prefer the british version `cancelled` with double `l`.

2019-06-18 09:53 UTC, aitorbouzas commented
Thanks @miguel-domatix !
Is that domain used for filtering? I don't see that method getting used anywhere.

2019-06-19 11:25 UTC, miguel-domatix commented
Hi @aitorbouzas, 
The last commit fix the team and assigned user behavior.

2019-06-20 13:19 UTC, aitorbouzas reviewed
LGTM. Fix travis.
Just want to know this below...

2019-06-20 13:19 UTC, aitorbouzas commented on helpdesk/models/helpdesk_ticket.py
> +    def _onchange_dominion_user_id(self):
I still don't get how this works. Am I missing something? Where's this domain applied?

2019-06-21 06:39 UTC, miguel-domatix commented
Este dominio se aplica a los campos de equipo y usuario asignado.
 - En caso de que no haya equipo, se pueden seleccionar todos los usurios.
 - En caso de que haya equipo, solo se podrán seleccionar usuarios de dicho
equipo.
 - En caso de que haya un usuario seleccionado, y se cambie el equipo, se
actualizará el campo de usuario acorde al equipo.


El jue., 20 jun. 2019 a las 15:19, Aitor Bouzas (<notifications@github.com>)
escribió:

> *@aitorbouzas* commented on this pull request.
>
> LGTM. Fix travis.
> Just want to know this below...
> ------------------------------
>
> In helpdesk/models/helpdesk_ticket.py
> <https://github.com/aitorbouzas/OCA-helpdesk/pull/6#discussion_r295800823>
> :
>
> > @@ -83,6 +88,20 @@ def _onchange_partner_id(self):
>              self.partner_name = self.partner_id.name
>              self.partner_email = self.partner_id.email
>
> +    @api.multi
> +    @api.onchange('team_id', 'user_id')
> +    def _onchange_dominion_user_id(self):
>
> I still don't get how this works. Am I missing something? Where's this
> domain applied?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aitorbouzas/OCA-helpdesk/pull/6?email_source=notifications&email_token=AMF7GYOEYBLJNMZ72JRXZYDP3N7VHA5CNFSM4HYGX7RKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4EYUNA#pullrequestreview-252283444>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMF7GYL3AUZUC5J35TMYGRDP3N7VHANCNFSM4HYGX7RA>
> .
>

2019-06-21 07:04 UTC, aitorbouzas commented
Thanks miguel, but the thing was that I didn't knew that an onchange function could return a domain for it to be applied atuomatically...
Ok, so just fix Travis and this will get merged.

2019-06-21 07:20 UTC, merged